### ISSUE TITLE
Broken link to Cipher Suite Order on README.md 

### ISSUE THREAD

**Issue by pronichkin** [Crosse/SchannelGroupPolicy#1]
README.md contains several suggestions for "Cipher Suite Order." One of them is entitled as "Steve Gibson's list." However, the link goes to Microsoft website (https://msdn.microsoft.com/library/windows/desktop/bb870930)--which, I assume, is not what you intended.

The link should be important, because other suggestion (Use IIS Crypto as a guide) is not terribly actionable. Unfortunately, you cannot copy the names from the tool, and re-typing them seems too error-prone.

**Comment by Crosse** [comment]
Thank you for bringing this to my attention. It looks like I had the correct link in the Markdown source, but I didn't actually use it. I've fixed it in 9dd7c26.
