### ISSUE TITLE
Move DTLS 1.0 in Weak Protocols ?

### ISSUE THREAD

**Issue by Harvester57** [Crosse/SchannelGroupPolicy#24]
Hi,

Just wondering why DTLS 1.0 is not shown under the "Weak Protocols" section, since it is based on TLS 1.1, which is considered weak in the template ?

If it's a bug, would be happy to open a PR to fix it, just let me know !

**Comment by Crosse** [comment]
That's a good question. I guess it got missed when I originally classified things. Would you be willing to submit a PR to fix that?

**Comment by Harvester57** [comment]
Yup, I'm on it :)

**Comment by Crosse** [comment]
Thank you for submitting that PR! I've not been keeping up with TLS protocols, ciphers, and hashes lately, so this was a welcome code change. I spot-checked things a bit. I'm wondering whether the plain Diffie-Hellman key exchange need to get moved to the Weak KeyEx list now? I think I typically see people saying use ECDH over DH, but don't know if that's enough to mark it as weak. 

Thanks again for the contribution!

**Comment by Harvester57** [comment]
I agree that ECDH should be prioritized over DH for key exchanges, but I don't think that DH is currently considered as weak, or at least it depends on the modulus size you are using. It has not been updated since 2020, but the KeyLength website offers a nice overview of currently recommended sizes, by several authoritative bodies : https://www.keylength.com/en/compare/

It appears you should be fine with a 2048 bits modulus, but probably safer with a 3072 bits modulus for the next decade applications. But in this case, you have to take into account the compatibility with older clients that do not support larger than 2048 bits modulus. 

Maybe I could port the two policies that control the client and server minimum key sizes ? I currently use it with a default of 2048 bits, with support for 3072 and 4096 bits modulus sizes (Schannel does not support larger modulus). You check it here : https://github.com/Harvester57/Security-ADMX/blob/main/AdditionalHardening.admx#L1401-L1446

**Comment by Harvester57** [comment]
Two propositions:

- Remove the 1024 bits modulus support, and make 2048 bits the new default;
- Keep the 1024 bits option, but make 2048 bits the new default with a `defaultItem` parameter pointing to 2048;

**Comment by Crosse** [comment]
> Maybe I could port the two policies that control the client and server minimum key sizes ?

That'd be a nice addition, I think! And re: support for 1024-bit moduli, I think I'd go with keeping the option but defaulting to 2048 if the setting is configured. My thinking is that this GPO shouldn't take something away if the user _needs_ it (backwards compat and all), but it should definitely steer the user towards better defaults (like differentiating between good and weak ciphers, etc.)
